GroupApp/GroupApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

GroupApp/urls.py
from django.contrib import admin
from django.urls import path,include
from MVapp import views
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from django.conf.urls.static import static
from django.conf import settings

class MyRegistrationView(RegistrationView):
    def get_success_url(self,user):
        return reverse('MVapp:register_profile')


urlpatterns = [
    path('',views.index,name='index'),
    path('MVapp/',include('MVapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/',
         MyRegistrationView.as_view(),
         name="registration_register"),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MVapp/urls.py
from django.urls import path
from MVapp import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'MVapp'

urlpatterns = [
path('', views.index, name='index'),
path('about/',views.about,name='about'),
path('genre/<slug:genre_name_slug>/',views.show_genre, name='show_genre'),
path('add_genre/', views.add_genre, name='add_genre'),
path('genre/<slug:genre_name_slug>/add_song/',views.add_song, name='add_song'),
path('song/<slug:song_name_slug>/',views.show_song,name='show_song'),
path('search/', views.search_results, name='search_results'),
path('song/<int:song_id>/comment/', views.comment_for_song, name='comment_for_song'),
path('register_profile/',views.register_profile,name="register_profile"),
path('like_song/', views.LikeSongView.as_view(), name='like_song'),
path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
path('profiles/',views.ListProfilesView.as_view(), name ='list_profiles'),
path('get_song_views/', views.get_song_views, name='get_song_views'),
path('tags/<slug:tag_slug>/', views.song_list_by_tag, name='song_list_by_tag'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MVapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Genre(models.Model):
    NAME_MAX_LENGTH = 128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default = 0)
    likes = models.IntegerField(default = 0)
    slug = models.SlugField(unique=True)
    

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Genre, self).save(*args, **kwargs)
    

    class Meta:
        verbose_name_plural = 'Genre'
    def __str__(self):
        return self.name
    
    
    
class Song(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default = 0)
    likes = models.IntegerField(default = 0)
    slug = models.SlugField(unique=True)
    artist = models.CharField(max_length = 200,blank = True)
    isExplicit = models.BooleanField(default=False)

    def save(self, *args, **kwargs):  
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 1
            while Song.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super(Song, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
   

class UserProfile(models.Model):
    ARTIST_LENGTH = 200
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isArtist = models.BooleanField(default=False)
    isMature = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    artistName = models.CharField(max_length=ARTIST_LENGTH, blank=True,help_text = "Only required if creating an Artist Account",)

    

    def save(self, *args, **kwargs):
        if self.isArtist:
            # If the user is an artist, populate artistName
            if not self.artistName:
                self.artistName = self.user.username  # Or any other default value
        else:
            # If the user is not an artist, make sure artistName is blank
            self.artistName = ""
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username
    

class Comment(models.Model):
    song=models.ForeignKey(Song,related_name='comments',on_delete=models.CASCADE)
    commenter = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

        def __str__(self):
            return f'Comment by {self.commenter} on {self.song}'

MVapp/forms.py
from django import forms
from MVapp.models import Genre, Song
from django.contrib.auth.models import User
from MVapp.models import UserProfile,Comment


class GenreForm(forms.ModelForm):
    name = forms.CharField(max_length=Genre.NAME_MAX_LENGTH,
                           help_text="Please enter the genre name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    slug = forms.CharField(widget=forms.HiddenInput(), required = False)

    class Meta:
        model = Genre
        fields = ('name',)


class SongForm(forms.ModelForm):
    title = forms.CharField(max_length=Song.TITLE_MAX_LENGTH,
                            help_text="Please enter the title of the song.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter only src URL of the youtube embed URL for the song's music video.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    isExplicit = forms.BooleanField(label="Explicit",required=False,help_text="Check this box if the song contains explicit content, such as strong language or mature themes.")
    


    class Meta:
        model = Song
        exclude = ('genre','artist')


   

 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')
    
    
class UserProfileForm(forms.ModelForm):
    isArtist = forms.BooleanField(label="Do you want to create an artist account?", required=False)
    isMature = forms.BooleanField(label="Mature Account", required=False,help_text="Explicit songs will not be shown to you if your account is not mature")
    artistName = forms.CharField(label="Artist Name",required=False,help_text="Only required if creating an Artist Account.")
    class Meta:
        model = UserProfile
        fields = ('picture','isMature','isArtist','artistName',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['song','commenter','body']
        exclude = ('song','commenter')

MVapp/views.py
from unicodedata import category
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse 
from django.shortcuts import redirect
from django.urls import reverse
from MVapp.forms import UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from datetime import datetime
from MVapp.models import Song,Genre,Comment
from MVapp.forms import SongForm,GenreForm,CommentForm
from django.db.models import Q
from django.views import View
from django.contrib.auth.models import User
from MVapp.models import UserProfile
from django.utils.decorators import method_decorator


# Create your views here.

def index(request):
    context_dict = {}
    genre_list = Genre.objects.order_by('-views')[:5]
    songs_list = Song.objects.order_by('-likes')[:5]
    context_dict = {}
    context_dict['genres'] = genre_list
    context_dict['songs'] = songs_list
    
    response = render(request, 'MVapp/index.html', context=context_dict)
    return response


def about(request):
    context_dict = {}
    response = render(request, 'MVapp/about.html', context=context_dict)
    return response

@login_required
def add_song(request, genre_name_slug):
    try:
        genre = Genre.objects.get(slug=genre_name_slug)
    except Genre.DoesNotExist:
        genre = None

    if genre is None:
        return redirect('/MVapp/')

    form = SongForm()
    if request.method == 'POST':
        form = SongForm(request.POST)
        if form.is_valid():
            if genre:
                song = form.save(commit=False)
                song.genre = genre  
                song.views = 0
                

                user_profile = request.user.userprofile
                song.artist = user_profile.artistName
                song.save()

                return redirect(reverse('MVapp:show_genre',
                                        kwargs={'genre_name_slug':genre_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form':form,'genre':genre}
    return render(request, 'MVapp/add_song.html',context_dict)

@login_required
def add_genre(request):
    form = GenreForm()
    if request.method == 'POST':
        form = GenreForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/MVapp/')
        else:
            print(form.errors)
    return render(request, 'MVapp/add_genre.html',{'form':form})

 
def show_genre(request, genre_name_slug):
    context_dict = {}
    try:
        genre = Genre.objects.get(slug=genre_name_slug)
        songs = Song.objects.filter(genre=genre).order_by('-views')
        context_dict['songs'] = songs
        context_dict['genre'] = genre
        genre.views = genre.views + 1
        genre.save()
    except Genre.DoesNotExist:
        context_dict['songs'] = None
        context_dict['genre'] = None

    return render(request,'MVapp/genre.html', context=context_dict)

def show_song(request, song_name_slug):
    context_dict = {}
    try:
        song = Song.objects.get(slug=song_name_slug)
        comments = Comment.objects.filter(song=song)
        context_dict['song'] = song
        context_dict['comments'] = comments
        song.views = song.views + 1
        song.save()
    except Song.DoesNotExist:
        context_dict['song'] = None

    return render(request,'MVapp/song.html', context=context_dict)


def search_results(request):

    if request.method == "POST":
        query = request.POST.get('q', '')
        songs = Song.objects.filter(title__contains=query)
        return render(request, 'MVapp/search_songs.html', {'query' :query, 'songs' : songs})
    else:
        return render(request, 'MVapp/search_songs.html',{})
    
@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('MVapp:index'))
        else:
            print(form.errors)
    
    context_dict = {'form':form}
    return render(request,'MVapp/profile_registration.html',context_dict)

class ProfileView(View):
    def get_user_details(self,username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'artistName':user_profile.artistName,'picture':user_profile.picture})

        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self,request,username):
        try:
            (user,user_profile,form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('MVapp:index'))
        
        context_dict = {'user_profile':user_profile,'selected_user':user,'form':form}
        return render(request,'MVapp/profile.html',context_dict)
    
    @method_decorator(login_required)
    def post(self,request,username):
        try:
            (user,user_profile,form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('MVapp:index'))
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('MVapp:profile',user.username)
        else:
            print(form.errors)
        context_dict = {'user_profile':user_profile,'selected_user':user,'form':form}
        return render(request,'MVapp/profile.html',context_dict)
    
class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self,request):
        profiles = UserProfile.objects.all()
        return render(request,'MVapp/list_profiles.html',{'user_profile_list':profiles})
    
@login_required
def comment_for_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.song = song 
            comment.commenter = request.user
            comment.save()
            return redirect('MVapp:show_song', song_name_slug=song.slug)

    else:
        comment_form = CommentForm()

    return render(request, 'MVapp/song.html',{'song':song,'comment_form':comment_form})

class LikeSongView(View):
    @method_decorator(login_required)
    def get(self,request):
        song_id= request.GET['song_id']
        try:
            song= Song.objects.get(id=int(song_id))
        except Song.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        song.likes = song.likes + 1
        song.save()

        return HttpResponse(song.likes)
    
def get_song_views(request):
    if request.method == 'GET':
        song_id = request.GET.get('song_id')
        try:
            song = Song.objects.get(id=song_id)
            return HttpResponse(str(song.views))
        except Song.DoesNotExist:
            return HttpResponse('Song not found', status=404)
    return HttpResponse('Invalid request method', status=400)
    





    

templates/MVapp/about.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class ="containter">
    <h1 class = "jumbotron-heading">This is the about page</h1>
    </div>
</div>
    <button class="btn btn-primary" id="about-btn">
        Click me - I'm using JQuery!
    </button>
    <div id="msg">Hello! I'm a further example for JQuery testing.</div>
{% endblock %}

templates/MVapp/add_genre.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Genre
{% endblock %}

 {% block body_block %}
 <div class="jumbotron p-4">
    <div class ="containter">
    <h1 class = "jumbotron-heading">Add a Genre</h1>
    </div>
 </div>
    
    <form id="genre_form" method="post" action="{% url 'MVapp:add_genre' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Genre" />
    </form> 
 {% endblock %}
    

templates/MVapp/add_song.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Song
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Song</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form role="form" id="song_form" method="post" action="/MVapp/genre/{{ genre.slug }}/add_song/" class="my-4">
                {% csrf_token %}
                {{ form.errors }}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Create Song</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/MVapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load MVapp_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        MVapp - {% block title_block %}TuneShare{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/MVapp.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'MVapp:index' %}">TuneShare <span data-feather="headphones"></span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'MVapp:index' %}">Home <span data-feather="home"></span></a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'MVapp:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/MVapp/">Logout <span data-feather="log-out"></span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'MVapp:add_genre' %}">Add Genre</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'MVapp:profile' user.username %}">Profile <span data-feather="user"></span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'MVapp:list_profiles' %}">All Profiles<span data-feather="users"></span></a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login<span data-feather="log-in"></span></a></li>
                        {% endif %}
                        <form class="form-inline ml-auto" method="POST" action="{% url 'MVapp:search_results' %}">
                            {% csrf_token %}
                            <input class="form-control form-control-sm mr-sm-2" type="search" placeholder="Search Songs" aria-label="Search" name="q">
                            <button class="btn btn-outline-primary btn-sm my-2 my-sm-0" type="submit"><span data-feather="search"></span></button>
                        </form>
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <div class="sidebar-heading">
                            <h4><u>Genres</u></h4> <!-- Add heading inside a div -->
                        </div>
                        {% block sidebar_block %}
                            {% get_genre_list genre %}
                        {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2024 MovieApp &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        <style>
            .sidebar-heading {
                padding-left: 15px; /* Adjust the padding value as needed */
                text-transform: none; /* Preserve original capitalization */
            }
        </style>
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js" %}"><\/script>')</script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/feather.min.js' %}"></script>
        <script src="{% static 'js/dashboard.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/MVapp-query.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/MVapp-ajax.js' %}" crossorigin="anonymous"></script>
    </body>
</html>

templates/MVapp/comment_form.html
<form action="{% url 'MVapp:comment_for_song' song_id=song.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_body">Body:</label>
        <textarea id="id_body" name="body" rows="4" cols="50" class="form-control">{{ comment_form.body }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Add comment</button>
</form>

templates/MVapp/genre.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if genre %}
        {{ genre.name }}
    {% else %}
        Unknown Genre
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if genre %}
    <div class="jumbotron p-4">
        <div class ="containter">
            <h1 class = "jumbotron-heading">{{ genre.name }}</h1>
        </div>
    </div>
    {% if user.is_authenticated %}
        {% if user.userprofile.isArtist %}
        <div class ="button-pad">
            <button class="btn btn-primary" id="add-song-btn">
            <a href="{% url 'MVapp:add_song' genre.slug %}">Add Song</a> <br/>
            </button>
        </div>
        {% else %}
        <div class ="button-pad">
            <button class="btn btn-primary" id="restricted-btn">
                <a href="{% url 'MVapp:profile' user.username %}">Create Artist Account to add song <span data-feather="edit"></span></a>
            </button>
        </div>
        {% endif %}
    {% endif %}
    {% if songs %}
    <ul class = "list-group">
        {% for song in songs %}
        <div>
        <li class = "list-group-item">
            <a href="{% url 'MVapp:show_song' song.slug %}">{{ song.title }} <span class="text-muted">- by {{ song.artist }}</span> </a>
            {% if song.views %}
            <span data-feather="eye"></span>  {{ song.views }}
            {% endif %}
        </li>
        <iframe width="280" height="157.5" src="{{ song.url }}" referrerpolicy="no-referrer-when-downgrade" frameborder="0" allowfullscreen></iframe>
        </div>
        {% endfor %}
    </ul>
    {% else %}
    <div class="jumbotron p-4">
        <div class ="containter">
        <strong>No songs currently in genre.</strong>
        </div>
    </div>
    {% endif %}
    {% else %}
    The specified genre does not exist.
    {% endif %}
{% endblock %}

templates/MVapp/genres.html
<ul class ="nav flex-column">
    {% if genres %}
        {% for g in genres %}
            {% if g == current_genre %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'MVapp:show_genre' g.slug %}"><span data-feather="disc"></span>{{ g.name }}</a>
            </li>
            {% else %}
            <li class ="nav-item">
                <a class="nav-link " href="{% url 'MVapp:show_genre' g.slug %}"><span data-feather="disc"></span>{{ g.name }}</a>
            </li>  
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no genres present.</li>
    {% endif %}
</ul>

templates/MVapp/index.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class ="containter">
        <h1 class = "jumbotron-heading">TuneShare says...</h1>
        <div>
           <h2 class ="h2">
            {% if user.is_authenticated %}
                Hi there {{ user.username }}
             {% else %}
                Hello!
             {% endif %}
        </h2>
        </div>
    </div>
</div>
<div class = "container">
    <div class = "row">
        <div class = "col mb-6">
            <div class = "card mb-6">
                <div class = "card-body">
                    <h2>Most Viewed Genres</h2>
                
                    <p class ="card-text">
                    {% if genres %}
                    <ul class="list-group">
                    {% for genre in genres %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'MVapp:show_genre' genre.slug %}">{{ genre.name }} </a>
                        <div class="ml-auto">
                            {{ genre.views }} <span data-feather="eye"></span>
                        </div>
                        </div>
                    </li>
                    {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no Genres present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class = "col-md-6">
            <div class="card mb-6">
                <div class = "card-body">
                    <h2>Most Liked Songs</h2>
                    <p class = "card-text">
                    {% if songs %}
                    <ul class="list-group">
                    {% for song in songs %}
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'MVapp:show_song' song.slug %}">{{ song.title }} 
                            <span class="text-muted">- by {{ song.artist }}</span>
                            </a>
                            <div class="ml-auto">
                            {{ song.likes }}
                            <span data-feather="thumbs-up"></span>
                            </div>
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no pages present.</strong>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/MVapp/profile.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">
            {{ selected_user.username }}'s Profile
        </h1>
    </div>
</div>
<div class="container">
    <div class="row">
        {{ MEDIA_URL }}
        {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture.url }}"
        width="300"
        height="300"
        alt="{{ selected_user.username }}'s profile image" 
        style="padding: 20px;">
        {% else %}
        <img src="{% static 'images/default_profile_pic.jpg' %}"
        width="300"
        height="300"
        alt="{{ selected_user.username }}'s profile image" 
        style="padding: 20px;">
        {% endif %}
        <br>
        
        <div>
            {% if selected_user == user %}
            {% if user_profile.isArtist %}
            <h3><u>Artist Account</u></h3>
            {% else %}
            <h3><u>User Account</u></h3>
            {% endif %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_picture">Picture:</label>
                    <input type="file" class="form-control-file" id="id_picture" name="picture">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="id_isArtist" name="isArtist" {% if user_profile.isArtist %}checked{% endif %}>
                    <label class="form-check-label" for="id_isArtist">Create Artist Account</label>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="id_isMature" name="isMature" {% if user_profile.isMature %}checked{% endif %}>
                    <label class="form-check-label" for="id_isMature">Mature Account</label>
                </div>
                <div class="form-group">
                    <label for="id_artistName">Artist Name:</label>
                    <input type="text" class="form-control" id="id_artistName" name="artistName" value="{{ user_profile.artistName }}">
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
            {% else %}
            <p>
                {% if user_profile.isArtist %}
                <strong>Artist Account:</strong>
                {{ user_profile.artistName }}
                {% else %}
                User Account
                {% endif %}
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/MVapp/song_list_by_tag.html
{% extends 'MVapp/base.html' %}
{% load staticfiles %}
{% block title_block %}
<h2>Songs tagged with " {{ tag.name }}"</h2>
{% for song in songs %}
	<p><a href="{% url 'MVapp:show_song' song.id %}">{{ song.title }}</a></p>
{% endfor %}


{% endblock %}